### ISSUE TITLE
Populated address values not clearing if not present in addressComponents

### ISSUE THREAD

**Issue by shawnvdp** [Vendic/hyva-checkout-google-address-autocomplete#10]
# Description
Currently, only address field types that are present in Google's response are dispatched for updating, leaving existing values.
This requires the user to find their match on the first try or to get lucky that all currently populated values' fields are present for the new address too.

https://github.com/Vendic/hyva-checkout-google-address-autocomplete/blob/b2c4b88fb990b06e0304719723b19c3baa835312/view/frontend/templates/checkout/google-autocomplete-js.phtml#L91

# Steps to reproduce:
1. Pick an address that populates 'City'
2. Pick an address that has no 'City'

# Observed behavior:
City stays populated despite the 2nd address not having a City.

# Expected behavior:
City should be cleared.

# Proposed solution
Remove the if statement and set the value to the value if present, otherwise an empty string, causing the input to be cleared.
```js
component.set(identifier, value ?? "");
```

**Comment by Tjitse-E** [comment]
@shawnvdp  goo idea. I like the proposed solution. Would you be willing to create a pull request?
